# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48619e760e5b48da2be8b86964af649e951d15c7528470cdbd96a756db7bce25cbb9a56c20bd333b9909352febbb6aaf5c41d2d1d052d2900fafded189c07f5c

test:
  secret_key_base: d9e25e4a161f1da5887aa0d47c2753f6aef31f51e173db90370f75af555a9c353af0cfdcdd65ca4a2e667ddaad7cf44193b4f08b2ec880a0f00f2c4e2725574c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
